apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vcjk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vcjk
    app.kubernetes.io/part-of: tkwch-fix-0075-0067-app
  name: devfile-sample-vcjk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vcjk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vcjk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-14-tenant/tkwch-fix-0075-0067-app/devfile-sample-vcjk@sha256:7313dbf6844e3d6143c87c05b499e0c2995cab58ab2c6d801cd1007c4b9672b3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
